name: xUnit Tests with Coverage

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '8.0.x'
  MIN_COVERAGE: 80  # Минимальное покрытие в %

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
          
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore --verbosity minimal
      
    - name: Run xUnit tests with coverage
      id: coverage
      run: |
        # Запуск тестов с покрытием через Coverlet
        dotnet test \
          --configuration Release \
          --no-build \
          --logger "trx;LogFileName=test-results.trx" \
          --collect:"XPlat Code Coverage" \
          --settings coverlet.runsettings \
          --results-directory TestResults
        
        # Альтернативный способ с MSBuild
        # dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
        
        # Поиск файла с покрытием
        COVERAGE_FILE=$(find TestResults -name "*.xml" -path "*/coverage.cobertura.xml" | head -1)
        echo "coverage_file=$COVERAGE_FILE" >> $GITHUB_OUTPUT
        
    - name: Check coverage threshold
      run: |
        # Находим файл покрытия
        COVERAGE_FILE=$(find TestResults -name "*.xml" -path "*/coverage.cobertura.xml" | head -1)
        
        # Извлекаем процент покрытия
        COVERAGE_LINE_RATE=$(grep -oP 'line-rate="\K[0-9.]+' "$COVERAGE_FILE")
        COVERAGE_PERCENT=$(echo "$COVERAGE_LINE_RATE * 100" | bc)
        
        # Округляем до 2 знаков
        COVERAGE_PERCENT_FORMATTED=$(printf "%.2f" $COVERAGE_PERCENT)
        
        echo "📊 Code Coverage: ${COVERAGE_PERCENT_FORMATTED}%"
        echo "coverage_percent=$COVERAGE_PERCENT_FORMATTED" >> $GITHUB_OUTPUT
        
        # Проверяем порог
        if (( $(echo "$COVERAGE_PERCENT < $MIN_COVERAGE" | bc -l) )); then
          echo "❌ Coverage is below minimum of ${MIN_COVERAGE}%"
          exit 1
        else
          echo "✅ Coverage meets minimum of ${MIN_COVERAGE}%"
        fi
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: TestResults/
        retention-days: 30
        
    - name: Upload to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./TestResults/**/coverage.cobertura.xml
        flags: xunit
        name: code-coverage-report
        fail_ci_if_error: false